package org.model;

// Generated 2013-4-21 11:41:17 by Hibernate Tools 3.2.2.GA

/**
 * Admin generated by hbm2java
 */
public class Admin implements java.io.Serializable {

	private Integer idAdmin;
	private String adName;
	private String adPassed;
	private int adType;
	private byte[] adPhoto;

	public Admin() {
	}

	public Admin(String adName, String adPassed, int adType) {
		this.adName = adName;
		this.adPassed = adPassed;
		this.adType = adType;
	}

	public Admin(String adName, String adPassed, int adType, byte[] adPhoto) {
		this.adName = adName;
		this.adPassed = adPassed;
		this.adType = adType;
		this.adPhoto = adPhoto;
	}

	public Integer getIdAdmin() {
		return this.idAdmin;
	}

	public void setIdAdmin(Integer idAdmin) {
		this.idAdmin = idAdmin;
	}

	public String getAdName() {
		return this.adName;
	}

	public void setAdName(String adName) {
		this.adName = adName;
	}

	public String getAdPassed() {
		return this.adPassed;
	}

	public void setAdPassed(String adPassed) {
		this.adPassed = adPassed;
	}

	public int getAdType() {
		return this.adType;
	}

	public void setAdType(int adType) {
		this.adType = adType;
	}

	public byte[] getAdPhoto() {
		return this.adPhoto;
	}

	public void setAdPhoto(byte[] adPhoto) {
		this.adPhoto = adPhoto;
	}

}
