package org.model;

// Generated 2013-4-21 11:41:17 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.Set;

/**
 * Album generated by hbm2java
 */
public class Album implements java.io.Serializable {

	private Integer idAlbum;
//	private int idSinger;
	private String abName;
	private Date abTime;
	private byte[] abPhoto;
	private String abAbstact;
	private Integer abScore;
	private Singer singer;
	private Set songs;

	public Album() {
	}

	public Album( String abName) {
		this.abName = abName;
	}

	public Album( String abName, Date abTime, byte[] abPhoto,
			String abAbstact, Integer abScore) {
		this.abName = abName;
		this.abTime = abTime;
		this.abPhoto = abPhoto;
		this.abAbstact = abAbstact;
		this.abScore = abScore;
	}

	public Integer getIdAlbum() {
		return this.idAlbum;
	}

	public void setIdAlbum(Integer idAlbum) {
		this.idAlbum = idAlbum;
	}

//	public int getIdSinger() {
//		return this.idSinger;
//	}
//
//	public void setIdSinger(int idSinger) {
//		this.idSinger = idSinger;
//	}

	public String getAbName() {
		return this.abName;
	}

	public void setAbName(String abName) {
		this.abName = abName;
	}

	public Date getAbTime() {
		return this.abTime;
	}

	public void setAbTime(Date abTime) {
		this.abTime = abTime;
	}

	public byte[] getAbPhoto() {
		return this.abPhoto;
	}

	public void setAbPhoto(byte[] abPhoto) {
		this.abPhoto = abPhoto;
	}

	public String getAbAbstact() {
		return this.abAbstact;
	}

	public void setAbAbstact(String abAbstact) {
		this.abAbstact = abAbstact;
	}

	public Integer getAbScore() {
		return this.abScore;
	}

	public void setAbScore(Integer abScore) {
		this.abScore = abScore;
	}

	public Singer getSinger() {
		return singer;
	}

	public void setSinger(Singer singer) {
		this.singer = singer;
	}

	public Set getSongs() {
		return songs;
	}

	public void setSongs(Set songs) {
		this.songs = songs;
	}

}
