package org.model;

// Generated 2013-4-21 17:29:57 by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * Comment generated by hbm2java
 */
public class Comment implements java.io.Serializable {

	private Integer idComment;
	private String usName;
	private int idSong;
	private Date cmTime;
	private String cmContent;

	public Comment() {
	}

	public Comment(String usName, int idSong, Date cmTime, String cmContent) {
		this.usName = usName;
		this.idSong = idSong;
		this.cmTime = cmTime;
		this.cmContent = cmContent;
	}

	public Integer getIdComment() {
		return this.idComment;
	}

	public void setIdComment(Integer idComment) {
		this.idComment = idComment;
	}

	public String getUsName() {
		return this.usName;
	}

	public void setUsName(String usName) {
		this.usName = usName;
	}

	public int getIdSong() {
		return this.idSong;
	}

	public void setIdSong(int idSong) {
		this.idSong = idSong;
	}

	public Date getCmTime() {
		return this.cmTime;
	}

	public void setCmTime(Date cmTime) {
		this.cmTime = cmTime;
	}

	public String getCmContent() {
		return this.cmContent;
	}

	public void setCmContent(String cmContent) {
		this.cmContent = cmContent;
	}

}
