package org.model;

// Generated 2013-4-21 11:41:17 by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * Message generated by hbm2java
 */
public class Message implements java.io.Serializable {

	private Integer idMessage;
	private String usName;
	private String msContent;
	private String contactInfo;
	private Date msTime;

	public Message() {
	}

	public Message(String usName, String msContent, Date msTime) {
		this.usName = usName;
		this.msContent = msContent;
		this.msTime = msTime;
	}

	public Integer getIdMessage() {
		return this.idMessage;
	}

	public void setIdMessage(Integer idMessage) {
		this.idMessage = idMessage;
	}

	public String getUsName() {
		return this.usName;
	}

	public void setUsName(String usName) {
		this.usName = usName;
	}

	public String getMsContent() {
		return this.msContent;
	}

	public void setMsContent(String msContent) {
		this.msContent = msContent;
	}

	public String getContactInfo() {
		return contactInfo;
	}

	public void setContactInfo(String contactInfo) {
		this.contactInfo = contactInfo;
	}

	public Date getMsTime() {
		return this.msTime;
	}

	public void setMsTime(Date msTime) {
		this.msTime = msTime;
	}

}
