package org.model;

// Generated 2013-4-21 17:11:43 by Hibernate Tools 3.2.2.GA

/**
 * SingerSongId generated by hbm2java
 */
public class SingerSongId implements java.io.Serializable {

	private int idSinger;
	private int idSong;

	public SingerSongId() {
	}

	public SingerSongId(int idSinger, int idSong) {
		this.idSinger = idSinger;
		this.idSong = idSong;
	}

	public int getIdSinger() {
		return this.idSinger;
	}

	public void setIdSinger(int idSinger) {
		this.idSinger = idSinger;
	}

	public int getIdSong() {
		return this.idSong;
	}

	public void setIdSong(int idSong) {
		this.idSong = idSong;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SingerSongId))
			return false;
		SingerSongId castOther = (SingerSongId) other;

		return (this.getIdSinger() == castOther.getIdSinger())
				&& (this.getIdSong() == castOther.getIdSong());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdSinger();
		result = 37 * result + this.getIdSong();
		return result;
	}

}
