package org.model;

import java.util.Set;

// Generated 2013-4-21 11:41:17 by Hibernate Tools 3.2.2.GA

/**
 * Singer generated by hbm2java
 */
public class Singer implements java.io.Serializable {

	private Integer idSinger;
	private String sgrName;
	private String sgrArea;
	private String sgrType;
	private Integer sgrScore;
	private byte[] sgrPhoto;
	private String sgrAbstract;
	private Set songs;
	private Set albums;

	public Singer() {
	}

	public Singer(String sgrName) {
		this.sgrName = sgrName;
	}

	public Singer(String sgrName, String sgrArea, Integer sgrScore,
			byte[] sgrPhoto, String sgrAbstract) {
		this.sgrName = sgrName;
		this.sgrArea = sgrArea;
		this.sgrScore = sgrScore;
		this.sgrPhoto = sgrPhoto;
		this.sgrAbstract = sgrAbstract;
	}

	public Integer getIdSinger() {
		return this.idSinger;
	}

	public void setIdSinger(Integer idSinger) {
		this.idSinger = idSinger;
	}

	public String getSgrName() {
		return this.sgrName;
	}

	public void setSgrName(String sgrName) {
		this.sgrName = sgrName;
	}

	public String getSgrArea() {
		return this.sgrArea;
	}

	public void setSgrArea(String sgrArea) {
		this.sgrArea = sgrArea;
	}

	public String getSgrType() {
		return sgrType;
	}

	public void setSgrType(String sgrType) {
		this.sgrType = sgrType;
	}

	public Integer getSgrScore() {
		return this.sgrScore;
	}

	public void setSgrScore(Integer sgrScore) {
		this.sgrScore = sgrScore;
	}

	public byte[] getSgrPhoto() {
		return this.sgrPhoto;
	}

	public void setSgrPhoto(byte[] sgrPhoto) {
		this.sgrPhoto = sgrPhoto;
	}

	public String getSgrAbstract() {
		return this.sgrAbstract;
	}

	public void setSgrAbstract(String sgrAbstract) {
		this.sgrAbstract = sgrAbstract;
	}

	public Set getSongs() {
		return songs;
	}

	public void setSongs(Set songs) {
		this.songs = songs;
	}

	public Set getAlbums() {
		return albums;
	}

	public void setAlbums(Set albums) {
		this.albums = albums;
	}

}
