package org.model;

// Generated 2013-4-21 17:11:43 by Hibernate Tools 3.2.2.GA

/**
 * SingerSong generated by hbm2java
 */
public class SingerSong implements java.io.Serializable {

	private SingerSongId id;

	public SingerSong() {
	}

	public SingerSong(SingerSongId id) {
		this.id = id;
	}

	public SingerSongId getId() {
		return this.id;
	}

	public void setId(SingerSongId id) {
		this.id = id;
	}

}
