package org.model;

// Generated 2013-4-21 11:41:17 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Song generated by hbm2java
 */
public class Song implements java.io.Serializable {

	private Integer idSong;
	private String sgName;
	private String sgType;
	private String sgRoute;
	private String sgMvRoute;
	private Integer sgSize;
	private Integer sgScore;
	private Date sgTime;
	private byte[] sgWords;
//	private Integer idAlbum;
	private String sgAbstract;
	private Set singers;
	private Album album;

	public Song() {
	}

	public Song(String sgName, String sgRoute) {
		this.sgName = sgName;
		this.sgRoute = sgRoute;
	}

	public Song(String sgName, String sgType, String sgRoute, String sgMvRoute,
			Integer sgSize, Integer sgScore, Date sgTime, byte[] sgWords,
			 String sgAbstract) {
		this.sgName = sgName;
		this.sgType = sgType;
		this.sgRoute = sgRoute;
		this.sgMvRoute = sgMvRoute;
		this.sgSize = sgSize;
		this.sgScore = sgScore;
		this.sgTime = sgTime;
		this.sgWords = sgWords;
//		this.idAlbum = idAlbum;
		this.sgAbstract = sgAbstract;
	}

	public Integer getIdSong() {
		return this.idSong;
	}

	public void setIdSong(Integer idSong) {
		this.idSong = idSong;
	}

	public String getSgName() {
		return this.sgName;
	}

	public void setSgName(String sgName) {
		this.sgName = sgName;
	}

	public String getSgType() {
		return this.sgType;
	}

	public void setSgType(String sgType) {
		this.sgType = sgType;
	}

	public String getSgRoute() {
		return this.sgRoute;
	}

	public void setSgRoute(String sgRoute) {
		this.sgRoute = sgRoute;
	}

	public String getSgMvRoute() {
		return this.sgMvRoute;
	}

	public void setSgMvRoute(String sgMvRoute) {
		this.sgMvRoute = sgMvRoute;
	}

	public Integer getSgSize() {
		return this.sgSize;
	}

	public void setSgSize(Integer sgSize) {
		this.sgSize = sgSize;
	}

	public Integer getSgScore() {
		return this.sgScore;
	}

	public void setSgScore(Integer sgScore) {
		this.sgScore = sgScore;
	}

	public Date getSgTime() {
		return this.sgTime;
	}

	public void setSgTime(Date sgTime) {
		this.sgTime = sgTime;
	}

	public byte[] getSgWords() {
		return this.sgWords;
	}

	public void setSgWords(byte[] sgWords) {
		this.sgWords = sgWords;
	}

//	public Integer getIdAlbum() {
//		return this.idAlbum;
//	}
//
//	public void setIdAlbum(Integer idAlbum) {
//		this.idAlbum = idAlbum;
//	}

	public String getSgAbstract() {
		return this.sgAbstract;
	}

	public void setSgAbstract(String sgAbstract) {
		this.sgAbstract = sgAbstract;
	}

	public Set getSingers() {
		return singers;
	}

	public void setSingers(Set singers) {
		this.singers = singers;
	}

	public Album getAlbum() {
		return album;
	}

	public void setAlbum(Album album) {
		this.album = album;
	}

}
