package org.model;

import java.util.Date;

// Generated 2013-4-21 17:11:43 by Hibernate Tools 3.2.2.GA

/**
 * Storelist generated by hbm2java
 */
public class Storelist implements java.io.Serializable {

	private int idStore;
	private Date stTime;
	private String relation;
	private String shareCont;
	private User user;
	private Song song;

	public Storelist() {
	}

	public int getIdStore() {
		return idStore;
	}

	public void setIdStore(int idStore) {
		this.idStore = idStore;
	}

	public Date getStTime() {
		return stTime;
	}

	public void setStTime(Date stTime) {
		this.stTime = stTime;
	}

	public String getRelation() {
		return relation;
	}

	public void setRelation(String relation) {
		this.relation = relation;
	}

	public String getShareCont() {
		return shareCont;
	}

	public void setShareCont(String shareCont) {
		this.shareCont = shareCont;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Song getSong() {
		return song;
	}

	public void setSong(Song song) {
		this.song = song;
	}

}
