package org.model;

import java.util.Set;

// Generated 2013-4-21 11:41:17 by Hibernate Tools 3.2.2.GA

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private String usName;
	private String usPasswd;
	private String usEmail;
	private byte[] usPhoto;
	private Set storeList;

	public User() {
	}

	public User(String usName, String usPasswd) {
		this.usName = usName;
		this.usPasswd = usPasswd;
	}

	public User(String usName, String usPasswd, String usEmail, byte[] usPhoto) {
		this.usName = usName;
		this.usPasswd = usPasswd;
		this.usEmail = usEmail;
		this.usPhoto = usPhoto;
	}

	public String getUsName() {
		return this.usName;
	}

	public void setUsName(String usName) {
		this.usName = usName;
	}

	public String getUsPasswd() {
		return this.usPasswd;
	}

	public void setUsPasswd(String usPasswd) {
		this.usPasswd = usPasswd;
	}

	public String getUsEmail() {
		return this.usEmail;
	}

	public void setUsEmail(String usEmail) {
		this.usEmail = usEmail;
	}

	public byte[] getUsPhoto() {
		return this.usPhoto;
	}

	public void setUsPhoto(byte[] usPhoto) {
		this.usPhoto = usPhoto;
	}

	public Set getStoreList() {
		return storeList;
	}

	public void setStoreList(Set storeList) {
		this.storeList = storeList;
	}

}
